name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: swift-actions/setup-swift@v1

      - name: checkout repo
        uses: actions/checkout@v3

      - name: run tests
        run: swift test
